---
default:
  rebalancer_max_receiving: 100
  bootstrapped: false
  collect_lua_garbage: false
  sched_ref_quota: 300
  rebalancer_max_sending: 1
  sync_timeout: 1
  rebalancer_disbalance_threshold: 1
  bucket_count: 30000
  sched_move_quota: 1
...
